import React from 'react';
import { Inter } from 'next/font/google';
import Footer from './layout/footer/footer';
import Navbar from './layout/navbar/navbar';
import Sidebar from './layout/sidebar/sidebar';
import type { Metadata } from 'next';
import './globals.scss';

const inter = Inter({ subsets: ['latin'] });

interface Props {
  children: React.ReactNode;
}

export default async function RootLayout({ children }: Props) {
  return (
    <html suppressHydrationWarning={true} lang='he' dir='rtl'>
      <body suppressHydrationWarning={true} className={inter.className}>
        <Navbar />

        <div className='relative'>
          <Sidebar />
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}

export const metadata: Metadata = {
  title: 'ganey-eden',
  description: 'Generated by Shay Bushary',
};
