import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from './layout/navbar/navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
interface Props {
  children: React.ReactNode;
}
export default async function RootLayout({ children }: Props) {

  return (
    <html suppressHydrationWarning={true} lang='he' dir='rtl'>
      <body suppressHydrationWarning={true} className={inter.className}>
        <Navbar />
        {children}
        <div>footer</div>
      </body>
    </html>
  );
}
