import { NextIntlClientProvider } from 'next-intl';
import { notFound } from 'next/navigation';

import '../globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from './navbar/navbar';

const inter = Inter({ subsets: ['latin'] });

export function generateStaticParams() {
  return [{ locale: 'en' }, { locale: 'es' }, { locale: 'he' }, { locale: 'ru' }];
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children, params: { locale } }: {
    children: React.ReactNode,
    params: { locale: string; };
  }) {

  let messages;
  try {
    messages = (await import(`../../messages/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }

  return (
    <html lang={locale} dir={locale == 'he' ? 'rtl' : 'ltr'}>
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Navbar />
          {children}
          <div>footer</div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
